# Generated by Django 2.1.8 on 2019-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190525_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='prize_percent',
            field=models.FloatField(default=0, verbose_name='prize percent'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is staff'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='is superuser'),
        ),
    ]
